{% set name = "microdot" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microdot-{{ version }}.tar.gz
  sha256: ddb2736d1a0f4972270cfc5747a21fd8a5deac655011fdba43882ef9ccc0c7af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - pip
  run:
    - python >=3.8

test:
  imports:
    - microdot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/miguelgrinberg/microdot
  doc_url: https://microdot.readthedocs.io/en/latest/
  summary: The impossibly small web framework for MicroPython
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
